name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push Docker image
        run: |
          IMAGE_TAG=$(echo "${{ github.sha }}" | head -c7)
          echo "Building image: ${{ secrets.DOCKER_USERNAME }}/appy-agency-website:$IMAGE_TAG"
          docker build -t "${{ secrets.DOCKER_USERNAME }}/appy-agency-website:$IMAGE_TAG" .
          docker push "${{ secrets.DOCKER_USERNAME }}/appy-agency-website:$IMAGE_TAG"

      - name: Deploy to VPS
        env:
          SSH_HOST: ${{ secrets.HOST }}
          SSH_USER: ${{ secrets.USERNAME }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          IMAGE_TAG=$(echo "${{ github.sha }}" | head -c7)
          echo "$SSH_PRIVATE_KEY" > deploy_key
          chmod 600 deploy_key
          ssh -i deploy_key -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} "
            docker pull ${{ secrets.DOCKER_USERNAME }}/appy-agency-website:$IMAGE_TAG
            docker stop nextjs-app || true
            docker rm nextjs-app || true
            docker run -d --name nextjs-app -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/appy-agency-website:$IMAGE_TAG
          "

      - name: Clean up
        run: shred -u deploy_key
